server {
    listen 80 default_server;
    server_name skillaz-digests.ru www.skillaz-digests.ru;
    root /var/www/digest;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /webhook/ {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
